import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatCheckboxModule,
  MatMenuModule,
  MatIconModule,
  MatToolbarModule,
  MatFormFieldModule,
  MatOptionModule,
  MatSelectModule,
  MatInputModule,
  MatSidenavModule,
  MatTooltipModule,
  MatGridListModule,
  MatStepperModule,
  MatCardModule,
  MatTabsModule,
  MatListModule,
  MatTableModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatProgressBarModule,
  MatDividerModule,
  MatProgressSpinnerModule
} from '@angular/material';

// Einbindung aller benötigter Material-Design-Komponenten
@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatInputModule,
    MatSidenavModule,
    MatTooltipModule,
    MatGridListModule,
    MatStepperModule,
    MatCardModule,
    MatTabsModule,
    MatListModule,
    MatTableModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatProgressBarModule,
    MatDividerModule,
    MatProgressSpinnerModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatToolbarModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    MatInputModule,
    MatSidenavModule,
    MatTooltipModule,
    MatGridListModule,
    MatStepperModule,
    MatCardModule,
    MatTabsModule,
    MatListModule,
    MatTableModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatProgressBarModule,
    MatDividerModule,
    MatProgressSpinnerModule
  ],
  providers: []
})
export class MdComponentsModule { }
